FORMAT: 1A

# Agenda

Agenda is a simple API allowing consumers to schedule meeting online.

# Group User

## User-Key [/v1/key]

### Get user key [GET /v1/key{?username,password}]


+ Parameters
    - username : `zhang3` (string, required) - User Name
    - password : `123` (required) - Password

+ Response 200 (application/json)

        {
            "key":"6384e2b2184bcbf58eccf10ca7a6563c"
        }
        
### Create a New User [POST]

+ Request (application/json)

        {
            "username":"li4",
            "password":"123",
            "email":"li4@163.com",
            "phone":"123"
        }

+ Response 201 (application/json)

    + Body

            {
                "id":1,
                "key":"9f9d51bc70ef21ca5c14f307980a29d8",
                "username":"li4",
                "password":"123",
                "email":"li4@163.com",
                "phone":"123"
            }

# Group Users

## Users Collection [/v1/users{?key}]

+ Parameters
    - key : `6384e2b2184bcbf58eccf10ca7a6563c` (string, required)

### List Users [GET]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "key": "******",
                "username":"zhang3",
                "password":"******",
                "email":"zhang3@163.com",
                "phone":"123"
            }, {
                "id":2,
                "key": "******",
                "username":"li4",
                "password":"******",
                "email":"li4@163.com",
                "phone":"123"
            }
        ]

### Delete User [DELETE]
    
+ Response 204

# Group Meetings

## Meetings Collection [/v1/meetings{?key}]

+ Parameters
    - key : `6384e2b2184bcbf58eccf10ca7a6563c` (string, required)

### List all meetings [GET]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "title":"Meeting-one",
                "host":"zhang3",
                "members":["li4"],
                "starttime":"2000/01/01/00:00",
                "endtime":"2001/01/01/00:00"
            },{
                "id":2,
                "title":"Meeting-two",
                "host":"li4",
                "members":["zhang3", "wang5"],
                "starttime":"2002/01/01/00:00",
                "endtime":"2003/01/01/00:00"
            }
        ]

### Create a meeting [POST]

+ Request (application/json)

        {
            "title":"Meeting-three",
            "members":["li4"],
            "starttime":"2004/01/01/00:00",
            "endtime":"2005/01/01/00:00"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 3,
                "title":"Meeting-three",
                "host":"zhang3",
                "members":["li4"],
                "starttime":"2004/01/01/00:00",
                "endtime":"2005/01/01/00:00"
            }

